### ISSUE TITLE
Topics List doesn't automatically refresh

### ISSUE THREAD

**Issue by jeffclaybrook** [Godsont/CRUD_MongoDB#2]
When a new topic is added or an existing topic is updated, the Topics List doesn't automatically update with the corresponding changes unless I manually refresh the page. However, it does automatically update when a topic is removed. I'm fiddling around with it and will update this if I figure it out

**Comment by jeffclaybrook** [comment]
Solved:

In addNote > page.jsx & components > EditTopicForm.jsx, handleSubmit should be:

if (res.ok) {
router.push("/")
router.refresh()
} else {
throw new Error("Unable to create/update topic")
}

I also created a Typescript version based upon this project that uses DaisyUI https://github.com/jeffclaybrook/crud-notes-app

**Comment by abir446** [comment]
Thanks for this, was not finding answers anywhere.
