### ISSUE TITLE
router.refresh() is not working

### ISSUE THREAD

**Issue by abir446** [Godsont/CRUD_MongoDB#3]
even if I write correctly or copy paste the code, it is not refreshing, I tried searching for the answer, found router.reload() option. It works neither.

**Comment by Ashen-Dissanayake** [comment]
Is this the path imported from 
`import { useRouter } from "next/navigation";`

**Comment by saim-x** [comment]
The import path should be "next/navigation" instead of "next/router".
This will fix your issue.
